[[SuiteSparseGraphBLAS]]
arch = "i686"
git-tree-sha1 = "220fdcce17a804e529f0df210fc8eb9eaa55d662"
libc = "musl"
os = "linux"

    [[SuiteSparseGraphBLAS.download]]
    sha256 = "03d9af80f0d959b5866c6cf43938a9a7596f351073669e474b6cd0061e218c7c"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparseGraphBLAS_jll.jl/releases/download/SuiteSparseGraphBLAS-v5.6.0+1/SuiteSparseGraphBLAS.v5.6.0.i686-linux-musl.tar.gz"
[[SuiteSparseGraphBLAS]]
arch = "aarch64"
git-tree-sha1 = "35bcd5bdecf5961ec033b763cfa03cb2c9337909"
libc = "musl"
os = "linux"

    [[SuiteSparseGraphBLAS.download]]
    sha256 = "5986d69dab908d88411a562f5a4ecc89380f5a4a9660f2e072340e67d8597e62"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparseGraphBLAS_jll.jl/releases/download/SuiteSparseGraphBLAS-v5.6.0+1/SuiteSparseGraphBLAS.v5.6.0.aarch64-linux-musl.tar.gz"
[[SuiteSparseGraphBLAS]]
arch = "i686"
git-tree-sha1 = "84aeb9753c9fa4540c36ff43b0eb07cdfc33db42"
os = "windows"

    [[SuiteSparseGraphBLAS.download]]
    sha256 = "3d2de162f6092276dfbd0471368533e3aca2870be6c8d4bad637a67c45ecb09d"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparseGraphBLAS_jll.jl/releases/download/SuiteSparseGraphBLAS-v5.6.0+1/SuiteSparseGraphBLAS.v5.6.0.i686-w64-mingw32.tar.gz"
[[SuiteSparseGraphBLAS]]
arch = "x86_64"
git-tree-sha1 = "736a32baf59c701ab70c6872b63a3003a92a50e7"
os = "windows"

    [[SuiteSparseGraphBLAS.download]]
    sha256 = "e1bdce8ac19247c776e8cf8c288cc91668a798af68c104045f3386f08f0ae13c"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparseGraphBLAS_jll.jl/releases/download/SuiteSparseGraphBLAS-v5.6.0+1/SuiteSparseGraphBLAS.v5.6.0.x86_64-w64-mingw32.tar.gz"
[[SuiteSparseGraphBLAS]]
arch = "armv7l"
git-tree-sha1 = "241c8d8c145a23d4ac52ddb8b5b76c887030da51"
libc = "glibc"
os = "linux"

    [[SuiteSparseGraphBLAS.download]]
    sha256 = "c33c76fd61281f1d9f2046a9cb2b797ec768f3ca2f82157d42cf0f485ebb380e"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparseGraphBLAS_jll.jl/releases/download/SuiteSparseGraphBLAS-v5.6.0+1/SuiteSparseGraphBLAS.v5.6.0.armv7l-linux-gnueabihf.tar.gz"
[[SuiteSparseGraphBLAS]]
arch = "armv7l"
git-tree-sha1 = "d779479a592fbb99b813391abdb770d4c78e8868"
libc = "musl"
os = "linux"

    [[SuiteSparseGraphBLAS.download]]
    sha256 = "10d62ccb497c7a5f50bd02cce96e30648902995c9085a652425cb47add4eb03e"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparseGraphBLAS_jll.jl/releases/download/SuiteSparseGraphBLAS-v5.6.0+1/SuiteSparseGraphBLAS.v5.6.0.armv7l-linux-musleabihf.tar.gz"
[[SuiteSparseGraphBLAS]]
arch = "i686"
git-tree-sha1 = "6f16b0e4a59302a96198b23b65732cbb8a56674b"
libc = "glibc"
os = "linux"

    [[SuiteSparseGraphBLAS.download]]
    sha256 = "654a2c90d6948bc3c26e4b78544140526139b8d2a5f563b5ff09ca12191fd46f"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparseGraphBLAS_jll.jl/releases/download/SuiteSparseGraphBLAS-v5.6.0+1/SuiteSparseGraphBLAS.v5.6.0.i686-linux-gnu.tar.gz"
[[SuiteSparseGraphBLAS]]
arch = "x86_64"
git-tree-sha1 = "2e9764f0a99e8c96745d44e943b4160b93cb813f"
libc = "glibc"
os = "linux"

    [[SuiteSparseGraphBLAS.download]]
    sha256 = "3d8cac965ce68d198b6ee7eb5ed0211ebba8d6974073711d65273dec9cbc4750"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparseGraphBLAS_jll.jl/releases/download/SuiteSparseGraphBLAS-v5.6.0+1/SuiteSparseGraphBLAS.v5.6.0.x86_64-linux-gnu.tar.gz"
[[SuiteSparseGraphBLAS]]
arch = "powerpc64le"
git-tree-sha1 = "aa12f53d3731a85d2263618affe97853c622d0be"
libc = "glibc"
os = "linux"

    [[SuiteSparseGraphBLAS.download]]
    sha256 = "a6a553cd219bf1be5fc9b28ee3e23e2994e97da21bdfbe8a5fe91b7de7f7ad8f"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparseGraphBLAS_jll.jl/releases/download/SuiteSparseGraphBLAS-v5.6.0+1/SuiteSparseGraphBLAS.v5.6.0.powerpc64le-linux-gnu.tar.gz"
[[SuiteSparseGraphBLAS]]
arch = "x86_64"
git-tree-sha1 = "86a594c578f8ce647b048a1238c135c92bc006c9"
os = "macos"

    [[SuiteSparseGraphBLAS.download]]
    sha256 = "7277e570e9c339ed4f68d29a0149e597948b45320f8010c667bca8396028bb74"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparseGraphBLAS_jll.jl/releases/download/SuiteSparseGraphBLAS-v5.6.0+1/SuiteSparseGraphBLAS.v5.6.0.x86_64-apple-darwin14.tar.gz"
[[SuiteSparseGraphBLAS]]
arch = "aarch64"
git-tree-sha1 = "0aee0c07b20515ec37e0faadc39974ab2f7b772d"
libc = "glibc"
os = "linux"

    [[SuiteSparseGraphBLAS.download]]
    sha256 = "2790edd73b6891549570014a67ea5925f41750078b66d55a74b7abec665cc0df"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparseGraphBLAS_jll.jl/releases/download/SuiteSparseGraphBLAS-v5.6.0+1/SuiteSparseGraphBLAS.v5.6.0.aarch64-linux-gnu.tar.gz"
[[SuiteSparseGraphBLAS]]
arch = "x86_64"
git-tree-sha1 = "0e097a3515942e0ae83c56490bea4c0b4378990a"
os = "freebsd"

    [[SuiteSparseGraphBLAS.download]]
    sha256 = "2b6cd2c75965115a2460cf9829181e47ffc8dd286fecd60a84f92f84a442b805"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparseGraphBLAS_jll.jl/releases/download/SuiteSparseGraphBLAS-v5.6.0+1/SuiteSparseGraphBLAS.v5.6.0.x86_64-unknown-freebsd11.1.tar.gz"
[[SuiteSparseGraphBLAS]]
arch = "x86_64"
git-tree-sha1 = "018256d2049b8a592c43431986df4a5f43f39560"
libc = "musl"
os = "linux"

    [[SuiteSparseGraphBLAS.download]]
    sha256 = "72360ef42ca68a5d92912612208862313a6ca7cfe84068fc9223408697b2ae43"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparseGraphBLAS_jll.jl/releases/download/SuiteSparseGraphBLAS-v5.6.0+1/SuiteSparseGraphBLAS.v5.6.0.x86_64-linux-musl.tar.gz"
